/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    ArrowIcon: typeof import('./src/components/ui/ArrowIcon.vue')['default']
    BackupIcon: typeof import('./src/components/ui/BackupIcon.vue')['default']
    CodeIcon: typeof import('./src/components/ui/CodeIcon.vue')['default']
    EditeHead: typeof import('./src/components/rightSideBar/EditeHead.vue')['default']
    EditeImg: typeof import('./src/components/rightSideBar/EditeImg.vue')['default']
    EditeText: typeof import('./src/components/rightSideBar/EditeText.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImgIcon: typeof import('./src/components/ui/ImgIcon.vue')['default']
    LeftSideBar: typeof import('./src/components/LeftSideBar.vue')['default']
    LeftSideBarButton: typeof import('./src/components/ui/LeftSideBarButton.vue')['default']
    ListIcon: typeof import('./src/components/ui/ListIcon.vue')['default']
    SelectBackups: typeof import('./src/components/rightSideBar/SelectBackups.vue')['default']
    SelectPage: typeof import('./src/components/rightSideBar/SelectPage.vue')['default']
    Settings: typeof import('./src/components/rightSideBar/Settings.vue')['default']
    SettingsIcon: typeof import('./src/components/ui/SettingsIcon.vue')['default']
    TextIcon: typeof import('./src/components/ui/TextIcon.vue')['default']
  }
}
